export const V3appInfo = {
    data: {
        "msg": "操作成功",
        "udidProflie": "https://apppp.cpolar.top/sign/mobileconfig/2024-10-25/USCIGBY8olcd.mobileconfig",
        "isUdidJump": 1,
        "code": 200,
        "data": {
            "antiCustomTitle": "",
            "antiCustomUrl": "",
            "appId": "4yGhydIf6K5PXq17e2b6rd",
            "approvalStatus": 1,
            "autoInstallFlag": "1",
            "autoPageName": 0,
            "backupUrl": "xxxx.com",
            "big": "27.19M",
            "build": "SourceRead",
            "bundle": "com.yuedu.sourceread.5Q974WKST6.J832KRQMUP",
            "chatLink": "",
            "comment": "这个应用真的太好用了，应用流畅不卡顿，画面清晰，操作便捷，玩法丰富多样，同事都在玩这个App，朋友们可以试试看，真的是非常的不错，强烈推荐推荐推荐！！！",
            "commentTitle": "非常不错的应用，推荐！",
            "createTime": "2024-08-31 21:31:56",
            "downloadType": 1,
            "downloadUrl": "apppp.cpolar.top",
            "guideType": "1",
            "img": "https://djb21no42vhk2.cloudfront.net/a17i8f8jkvn57lnzklqfwwy3vw5sp864.png?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kamIyMW5vNDJ2aGsyLmNsb3VkZnJvbnQubmV0L2ExN2k4Zjhqa3ZuNTdsbnprbHFmd3d5M3Z3NXNwODY0LnBuZyIsIkNvbmRpdGlvbiI6eyJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn0sIkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzI5ODQwNDg0fX19XX0_&Signature=riDHWg4FHRiOSKj5drzm1Fx1wQEfHBIeXCFeZQ8cJh5puOVTXmVh43iVhDvpbNanv~FrpqG3prpViLVlmZ8aB8tgJ07vyggLFdQEvOTppzn8WgishfJVNl7no4KdTnuyLQ77ukjvOKRFeAkKi8lCeDxCCyIlSxxoryamftLpTDnQTLMS4ObALY0TDypFAGjL2YNdp69fi7OtFIWkKSk5kzsX0RObpQN3X-DVo4jR0Hjz3mxs6y7JrFojOsmeaGgfdGE83pTU2DU6xfSiDi9iQHjR1HfcnHodwnpWIGpJkj5CBlk2c-9Jt-JDVsTx4~vUd4kJwdpKb1ZWSsyVVoLlDA__&Key-Pair-Id=APKATCKASLRMUDYFB2GS",
            "lang": 0,
            "mainShortPrefix": "6dsbgw",
            "message": 0,
            "name": "源阅读",
            "onlyDownload": 0,
            "openWay": 0,
            "remark": "",
            "requireOsVersion": "13.0",
            "signType": 0,
            "size": 28508421,
            "status": 1,
            "subShortPrefix": "bz5cdthg",
            "testType": 0,
            "type": "1",
            "updateTime": "2024-10-25 15:14:09",
            "version": "1.5.0",
            "warning": 0,
            "way": 1,
            "webclip": 0
        }
    }
}